# Generated by Django 5.2.1 on 2025-05-19 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhSachPhiDongGop',
            fields=[
                ('ten_phi', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('so_tien_goi_y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='HoKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_can_ho', models.CharField(max_length=10)),
                ('tang', models.IntegerField()),
                ('toa_nha', models.CharField(max_length=30)),
                ('ngay_lap', models.DateField(blank=True, null=True)),
                ('ngay_chuyen_di', models.DateField(blank=True, null=True)),
                ('dien_tich', models.FloatField(blank=True, null=True)),
                ('so_xe_may', models.IntegerField(blank=True, null=True)),
                ('so_o_to', models.IntegerField(blank=True, null=True)),
                ('thoi_gian_bat_dau_o', models.DateField(blank=True, null=True)),
                ('thoi_gian_ket_thuc_o', models.DateField(blank=True, null=True)),
                ('trang_thai', models.CharField(choices=[('Đang ở', 'Đang ở'), ('Đã rời đi', 'Đã rời đi')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vai_tro', models.CharField(choices=[('Quản lý chung cư', 'Quản lý chung cư'), ('Kế toán', 'Kế toán')], max_length=30)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='DongGopPhi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_dong', models.DateField()),
                ('so_tien_dong', models.FloatField()),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('phi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.danhsachphidonggop')),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='CapNhatPhiSinhHoat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tien_dien', models.FloatField(blank=True, null=True)),
                ('tien_nuoc', models.FloatField(blank=True, null=True)),
                ('tien_internet', models.FloatField(blank=True, null=True)),
                ('thang', models.IntegerField()),
                ('nam', models.IntegerField()),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=100)),
                ('ngay_sinh', models.DateField()),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ')], max_length=3)),
                ('ma_can_cuoc', models.CharField(max_length=15)),
                ('so_dien_thoai', models.CharField(max_length=15)),
                ('trang_thai', models.CharField(choices=[('Đang sinh sống', 'Đang sinh sống'), ('Đã chuyển đi', 'Đã chuyển đi'), ('Đã qua đời', 'Đã qua đời')], max_length=20)),
                ('thoi_gian_chuyen_den', models.DateField()),
                ('thoi_gian_chuyen_di', models.DateField(blank=True, null=True)),
                ('quan_he_voi_chu_ho', models.CharField(blank=True, max_length=30, null=True)),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='LichSuNhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian', models.DateField()),
                ('hanh_dong', models.CharField(choices=[('Chuyển đến', 'Chuyển đến'), ('Chuyển đi', 'Chuyển đi'), ('Qua đời', 'Qua đời'), ('Cập nhật thông tin', 'Cập nhật thông tin')], max_length=30)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.nhankhau')),
            ],
        ),
        migrations.AddField(
            model_name='hokhau',
            name='chu_ho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chu_ho_cua_ho_khau', to='apartment_management.nhankhau'),
        ),
        migrations.CreateModel(
            name='PhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gui', models.DateField()),
                ('noi_dung', models.TextField()),
                ('trang_thai', models.CharField(choices=[('Chưa xử lý', 'Chưa xử lý'), ('Đang xử lý', 'Đang xử lý'), ('Đã xử lý', 'Đã xử lý')], default='Chưa xử lý', max_length=20)),
                ('phan_hoi', models.TextField(blank=True, null=True)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.nhankhau')),
            ],
        ),
        migrations.CreateModel(
            name='Phi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_phi', models.CharField(choices=[('Dịch vụ', 'Dịch vụ'), ('Gửi xe', 'Gửi xe'), ('Quản lý', 'Quản lý'), ('Sinh hoạt', 'Sinh hoạt')], max_length=20)),
                ('gia_phi', models.FloatField()),
                ('tien_nop_moi_thang', models.FloatField()),
                ('nam', models.IntegerField()),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhiTheoThang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang', models.IntegerField()),
                ('so_tien', models.FloatField()),
                ('phi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.phi')),
            ],
        ),
        migrations.CreateModel(
            name='PhuongTien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai_phuong_tien', models.CharField(choices=[('Ô tô', 'Ô tô'), ('Xe máy', 'Xe máy')], max_length=10)),
                ('bien_so', models.CharField(max_length=50)),
                ('mau', models.CharField(max_length=50)),
                ('mo_ta', models.TextField(blank=True, null=True)),
                ('ho_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.hokhau')),
            ],
        ),
        migrations.CreateModel(
            name='TamTruTamVang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loai', models.CharField(choices=[('Tạm trú', 'Tạm trú'), ('Tạm vắng', 'Tạm vắng')], max_length=10)),
                ('thoi_gian_bat_dau', models.DateField()),
                ('thoi_gian_ket_thuc', models.DateField()),
                ('ly_do', models.CharField(max_length=255)),
                ('nhan_khau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment_management.nhankhau')),
            ],
        ),
    ]
