# Generated by Django 5.2.1 on 2025-05-26 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hokhau',
            name='thoi_gian_bat_dau_o',
        ),
        migrations.RemoveField(
            model_name='hokhau',
            name='thoi_gian_ket_thuc_o',
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hokhau',
            name='trang_thai',
            field=models.CharField(choices=[('Đang ở', 'Đang ở'), ('Đã rời đi', 'Đã rời đi'), ('Đã qua đời', 'Đã qua đời')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='vai_tro',
            field=models.CharField(choices=[('Quản lý', 'Quản lý'), ('Kế toán', 'Kế toán')], max_length=30),
        ),
    ]
