# Generated by Django 5.2.1 on 2025-06-02 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0002_remove_hokhau_thoi_gian_bat_dau_o_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='danhsachphidonggop',
            name='noi_dung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='nguoidung',
            name='ho_ten',
            field=models.CharField(default='Unkhown', max_length=100),
        ),
        migrations.AlterField(
            model_name='hokhau',
            name='trang_thai',
            field=models.CharField(choices=[('Đang ở', 'Đang ở'), ('Đã rời đi', 'Đã rời đi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='so_dien_thoai',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='nguoidung',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='ma_can_cuoc',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='phuongtien',
            name='bien_so',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='phuongtien',
            name='mau',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='LichSuNhanKhau',
        ),
    ]
