# Generated by Django 5.2.1 on 2025-06-09 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0004_alter_nguoidung_ho_ten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phananh',
            name='nhan_khau',
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='trang_thai',
            field=models.CharField(choices=[('Đang sinh sống', 'Đang sinh sống'), ('Đã chuyển đi', 'Đã chuyển đi'), ('Đã qua đời', 'Đã qua đời')], default='Đang sinh sống', max_length=20),
        ),
    ]
