# Generated by Django 5.2.1 on 2025-06-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0005_remove_phananh_nhan_khau_alter_nhankhau_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phi',
            name='tien_nop_moi_thang',
        ),
        migrations.AddField(
            model_name='danhsachphidonggop',
            name='ngay_bat_dau',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='danhsachphidonggop',
            name='ngay_ket_thuc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='capnhatphisinhhoat',
            unique_together={('ho_khau', 'thang', 'nam')},
        ),
        migrations.AlterUniqueTogether(
            name='chitietphitheothang',
            unique_together={('phi', 'thang')},
        ),
        migrations.AlterUniqueTogether(
            name='donggopphi',
            unique_together={('phi', 'ho_khau', 'ngay_dong')},
        ),
    ]
