# Generated by Django 5.2.1 on 2025-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0006_remove_phi_tien_nop_moi_thang_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhanAnh',
        ),
        migrations.RemoveField(
            model_name='phi',
            name='gia_phi',
        ),
        migrations.AddField(
            model_name='phi',
            name='gia_phi_dich_vu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phi',
            name='gia_phi_gui_o_to',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phi',
            name='gia_phi_gui_xe_may',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='phi',
            name='gia_phi_quan_ly',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
