# Generated by Django 5.2.1 on 2025-06-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0007_delete_phananh_remove_phi_gia_phi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_dich_vu',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_gui_o_to',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_gui_xe_may',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_quan_ly',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
