# Generated by Django 5.2.1 on 2025-06-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0008_alter_phi_gia_phi_dich_vu_alter_phi_gia_phi_gui_o_to_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitietphitheothang',
            unique_together=set(),
        ),
    ]
