# Generated by Django 5.2.1 on 2025-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0010_alter_chitietphitheothang_so_tien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietphitheothang',
            name='so_tien',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_dich_vu',
            field=models.FloatField(blank=True, default=16500, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_gui_o_to',
            field=models.FloatField(blank=True, default=1200000, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_gui_xe_may',
            field=models.FloatField(blank=True, default=70000, null=True),
        ),
        migrations.AlterField(
            model_name='phi',
            name='gia_phi_quan_ly',
            field=models.FloatField(blank=True, default=7000, null=True),
        ),
    ]
