# Generated by Django 5.2.1 on 2025-06-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment_management', '0011_alter_chitietphitheothang_so_tien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chitietphitheothang',
            name='da_dong',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phi',
            name='nam',
            field=models.IntegerField(default=2025),
        ),
    ]
